### ISSUE TITLE
bug: missing field `gasPrice` panic error

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/ef-tests#455]
# Bug Report

**Kakarot version:**

Kakarot sha 7686fbf022d99ce01927eb488ad59f0a0ec7ce5d

**Current behavior:**

When running stEIP1559, stEIP2930, stExample

```
thread 'blockchain_tests::st_eip1559' panicked at 'test case should load: Io { path: "/workspaces/ef-tests/crates/ef-testing/ethereum-tests/GeneralStateTests/stEIP1559/intrinsic.json", error: "missing field `gasPrice` at line 1 column 2890321" }', /workspaces/ef-tests/crates/ef-testing/src/traits/mod.rs:56:58

thread 'blockchain_tests::st_eip2930' panicked at 'test case should load: Io { path: "/workspaces/ef-tests/crates/ef-testing/ethereum-tests/GeneralStateTests/stEIP2930/coinbaseT2.json", error: "missing field `gasPrice` at line 1 column 5326" }', /workspaces/ef-tests/crates/ef-testing/src/traits/mod.rs:56:58

thread 'blockchain_tests::st_example' panicked at 'test case should load: Io { path: "/workspaces/ef-tests/crates/ef-testing/ethereum-tests/GeneralStateTests/stExample/basefeeExample.json", error: "missing field `gasPrice` at line 1 column 9702" }', /workspaces/ef-tests/crates/ef-testing/src/traits/mod.rs:56:58
```

**Comment by greged93** [comment]
Will be added in #473, comes from the fact that the structure we deserialize in should have Option as a type for the gas_price field.

**Comment by greged93** [comment]
Completed by https://github.com/kkrt-labs/ef-tests/pull/473
